spring:
  application:
    name: Liquibase
  h2:
    console:
      enabled: true
  liquibase:
    change-log: src/main/resources/db/changelog/${phase-release}/db.changelog.xml

  datasource:
    url: jdbc:h2:./data/database;AUTO_SERVER=TRUE
    username: sa
    password:

  sql:
    init:
      mode: always