-- liquibase formatted sql

-- changeset zahid_khan2:1766939108812-3
CREATE TABLE IF NOT EXISTS STUDENT (
                         ID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         NAME VARCHAR(255) NOT NULL,
                         ADDRESS VARCHAR(500),
                         CONSTRAINT STUDENT_PK PRIMARY KEY (ID)
);
