-- liquibase formatted sql

-- changeset zahid_khan2:1766939108811-1 splitStatements:false
CREATE TABLE STUDENT (ID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, NAME VARCHAR(255) NOT NULL, ADDRESS VARCHAR(500), CONSTRAINT CONSTRAINT_B PRIMARY KEY (ID));

-- changeset zahid_khan2:1766939108811-2 splitStatements:false
INSERT INTO STUDENT (ID, NAME, ADDRESS) VALUES (1, 'Jane Doe', '123 Maple Avenue, Springfield');
INSERT INTO STUDENT (ID, NAME, ADDRESS) VALUES (2, 'Jane Doe', '123 Maple Avenue, Springfield');
INSERT INTO STUDENT (ID, NAME, ADDRESS) VALUES (3, 'Zahid Khan', '123 Maple Avenue, Springfield');
INSERT INTO STUDENT (ID, NAME, ADDRESS) VALUES (4, 'Sarwat Ali', '123 Maple Avenue, Springfield');
INSERT INTO STUDENT (ID, NAME, ADDRESS) VALUES (5, 'SA', '123 Maple Avenue, Springfield');

